### ISSUE TITLE
Models TODO

### ISSUE THREAD

**Issue by QartemisT** [DeadlyBossMods/DBM-Classic#742]
Dungeon models:
- [ ] Blackfathrom Deeps
- [ ] Blackrock Depths
- [ ] Blackrock Spire (Lower)
- [ ] Blackrock Spire (Upper)
- [ ] Deadmines
- [ ] Dire Maul
- [ ] Gnomeregan
- [ ] Maraudon
- [ ] Ragefire Chasm
- [ ] Razorfen Downs
- [ ] Razorfen Kraul
- [ ] Scarlet Monastery
- [ ] Scholomance
- [ ] Shadowfang Keep
- [ ] Stormwind Stockade
- [ ] Stratholme
- [ ] Sunken Temple
- [ ] Uldaman
- [ ] Wailing Caverns
- [ ] Zul'Farrak

Raid models:
- [ ] Naxxramas
- [ ] Ahn'Qiraj Temple
- [ ] Ruins of Ahn'Qiraj
- [ ] Zul'Gurub
- [ ] Blackwing LAir
- [ ] Azeroth (Classic)
- [ ] Molten Core
- [ ] Onyxia's Lair
